"""Initial migration.

Revision ID: 51bdf36dee6d
Revises: 
Create Date: 2022-02-28 13:34:20.196616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bdf36dee6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Person',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Förnamn', sa.String(length=50), nullable=False),
    sa.Column('Efternamn', sa.String(length=50), nullable=False),
    sa.Column('Address', sa.String(length=50), nullable=False),
    sa.Column('Stad', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Accounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Kontotyp', sa.String(length=10), nullable=False),
    sa.Column('Skapad', sa.DateTime(), nullable=False),
    sa.Column('Saldo', sa.Integer(), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['Person.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Accounts')
    op.drop_table('Person')
    # ### end Alembic commands ###
